### PR TITLE
Fix/retro compatibility

### LINKED ISSUE #7: Support gitbook 1.x.x's syntax
Be retrocompatible :)

### PR DESCRIPTION
**Pull request by AaronO**
Fixes #7

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -38,5 +40,13 @@ module.exports = {
                 });
             }
         }
+    },
+    hooks: {
+        "page:before": function(page) {
+            if(page.type != "markdown") {
+                return;
```
Comment (SamyPesse) [inline index.js]: This will break everything, you need to return the page.
